#!/usr/bin/env node
/**
 * Compose jobs/<name>.md from fragments.
 *
 * ## Why generate instead of hand-editing
 *
 * Seven of the eight scout prompts shared a byte-identical seven-line
 * preamble, maintained by copy-paste. It drifted: ux-audit.md silently lost
 * "Cite source URLs in every issue" and compressed the untrusted-data warning,
 * so one scout had been filing to a weaker standard than the other six for as
 * long as anyone can tell. docs/harness-audit-2026-08.md calls that preamble
 * "a template that was extracted by copy-paste instead of by mechanism".
 *
 * This is the mechanism. The shared text exists once, in
 * jobs/_preamble.scout.md and jobs/_rules.enablement.md; per-job content lives
 * in jobs/missions/<name>.md; the composed jobs/<name>.md is generated and
 * committed.
 *
 * ## Why the output is committed rather than composed at run time
 *
 * jobs/<name>.md stays exactly what run-job.sh reads (`cat jobs/$JOB.md`), so
 * the runner contract is untouched and a job prompt is still one file a human
 * can read whole. `--check` in npm test is what stops the generated file being
 * hand-edited, the same drift guard scripts/vs-pages.mjs uses for vs pages.
 *
 * Slots come from harness.config.json, so labels and per-run caps have one
 * source of truth shared with the validator.
 *
 * Usage:
 *   node scripts/compose-jobs.mjs --build   # write jobs/<name>.md
 *   node scripts/compose-jobs.mjs --check   # fail if any file is stale
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ROOT } from './core/paths.mjs';
import { config } from './core/config.mjs';

const JOBS = path.join(ROOT, 'jobs');
const MISSIONS = path.join(JOBS, 'missions');

const GENERATED_NOTE =
  '<!-- GENERATED by scripts/compose-jobs.mjs from jobs/missions/ + jobs/_*.md — edit those, then run `npm run jobs`. -->';

/* ------------------------------------------------------------ fragments -- */

/**
 * Minimal front matter: `key: value` lines between --- fences. Deliberately
 * not YAML -- CLAUDE.md forbids adding dependencies, and the whole schema is
 * five optional string keys.
 */
export function parseFrontMatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error('mission file has no --- front matter block');

  const meta = {};
  for (const line of m[1].split('\n')) {
    if (!line.trim()) continue;
    const kv = line.match(/^([A-Za-z][A-Za-z0-9]*):\s*(.*)$/);
    if (!kv) throw new Error(`unparseable front-matter line: ${line}`);
    let value = kv[2].trim();
    // Quoted values keep leading/trailing spaces, which capNote needs.
    if (/^".*"$/.test(value)) value = value.slice(1, -1);
    meta[kv[1]] = value;
  }
  return { meta, body: m[2].trimEnd() };
}

/** `ok|plan` -> `<agent-ok|needs-plan>`; `plan` -> `needs-plan`. */
function renderLabelChoice(spec) {
  const names = spec.split('|').map((slot) => {
    const label = config.labels[slot.trim()];
    if (!label) throw new Error(`labelChoice names unknown slot '${slot}' (see harness.config.json labels)`);
    return label;
  });
  return names.length === 1 ? names[0] : `<${names.join('|')}>`;
}

export function compose(job, source) {
  const { meta, body } = parseFrontMatter(source);
  const parts = [GENERATED_NOTE, ''];

  if (meta.role === 'scout') {
    const cap = config.caps.byJob[job];
    if (cap === undefined) throw new Error(`no caps.byJob entry for '${job}' in harness.config.json`);

    const preamble = fs
      .readFileSync(path.join(JOBS, '_preamble.scout.md'), 'utf8')
      .trimEnd()
      .replace('{{LABEL_CHOICE}}', renderLabelChoice(meta.labelChoice))
      .replace('{{TITLE_FORM}}', meta.titleForm)
      .replace('{{EVIDENCE}}', meta.evidence)
      .replace('{{CAP}}', String(cap))
      .replace('{{CAP_NOTE}}', meta.capNote ?? '')
      .replace('{{LABEL_PLAN}}', config.labels.plan);

    parts.push(preamble, '');
  } else if (meta.role !== 'control') {
    throw new Error(`unknown role '${meta.role}' (expected scout or control)`);
  }

  parts.push(body, '');
  parts.push(fs.readFileSync(path.join(JOBS, '_rules.enablement.md'), 'utf8').trimEnd());

  return `${parts.join('\n')}\n`;
}

/* ---------------------------------------------------------------- files -- */

export const missionFiles = () =>
  fs
    .readdirSync(MISSIONS)
    .filter((f) => f.endsWith('.md'))
    .sort();

export function composeAll() {
  const out = new Map();
  for (const file of missionFiles()) {
    const job = file.replace(/\.md$/, '');
    out.set(job, compose(job, fs.readFileSync(path.join(MISSIONS, file), 'utf8')));
  }
  return out;
}

/* ------------------------------------------------------------------ CLI -- */

function main(argv) {
  const composed = composeAll();

  if (argv.includes('--check')) {
    const stale = [];
    for (const [job, want] of composed) {
      const target = path.join(JOBS, `${job}.md`);
      const got = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
      if (got !== want) stale.push(job);
    }
    if (stale.length > 0) {
      console.error(`Stale composed job prompts: ${stale.join(', ')}`);
      console.error('Run `npm run jobs` and commit the result. Do not hand-edit jobs/<name>.md.');
      return 1;
    }
    console.log(`All ${composed.size} job prompts are up to date.`);
    return 0;
  }

  if (argv.includes('--build')) {
    for (const [job, text] of composed) {
      fs.writeFileSync(path.join(JOBS, `${job}.md`), text);
    }
    console.log(`Composed ${composed.size} job prompts from jobs/missions/.`);
    return 0;
  }

  console.error('usage: node scripts/compose-jobs.mjs --build | --check');
  return 64;
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) process.exit(main(process.argv.slice(2)));
